### ISSUE TITLE
Bitcode mismatch between NEO Swift and GoNEOWallet

### ISSUE THREAD

**Issue by lm2s** [CityOfZion/neo-swift#28]
There's a mismatch between the NEO Swift project (enabled) and the GoNEOWallet framework (disabled) which results in a build error when integrating the NEO Swift framework with another project.

Possible solutions:
- Build a bitcode-enabled GoNEOWallet framework
- Disable bitcode in NEO Swift (this forces projects integrating the NEO Swift SDK to have bitcode disabled as well)

**Comment by saltyskip** [comment]
This is a limitation of building the framework with Go-Mobile, the toolchain is not capable of building LLVM bitcode, so without a solid ECDSA library in Swift we'll have to disable bitcode on all projects. I believe it should be ok, we just merged in this PR #25

If you're importing into an xcode project then disable bitcode in that project and you should be good to go
