### ISSUE TITLE
Remove SwiftBaseX and CryptoSwift at all Possible

### ISSUE THREAD

**Issue by saltyskip** [CityOfZion/neo-swift#4]
Should be relatively easy to get rid of SwiftBaseX. I think I'm now only using a couple of extensions there anyway. If not possible, need to update readme for carthage dependencies

**Comment by lm2s** [comment]
I'm mostly done removing SwiftBaseX and CryptoSwift, just need to run a few more tests and I'll make a PR.

**Comment by saltyskip** [comment]
Done, thanks @lm2s
