### ISSUE TITLE
How to create a keystoreJSON file?

### ISSUE THREAD

**Issue by AlleniCode** [CityOfZion/neo-swift#61]
How to create a keystoreJSON file?

**Comment by saltyskip** [comment]
You mean NEP2 Compatible wallet?

**Comment by AlleniCode** [comment]
A keystoreJSON file is that can resume a wallet account with your password, it's like this:

{"version":3,"id":"3FF58E74-CA59-4BF0-8CFF-59E87AC063BD","crypto":{"ciphertext":"cfecb3c34890ade10f4a9b699c5f64bf9e071037f14f4b555a29e629effdab8b","cipherparams":{"iv":"aed6e4588a004cabbc06347fabb04090"},"kdf":"scrypt","kdfparams":{"r":8,"p":1,"n":1024,"dklen":32,"salt":"ad5085614c21919db9b6f469e58239733950aa4235f8d6dbac5dd3847803e88f"},"mac":"9eb9d47d2997d4dbe92bf20c670892b6dd7d9b2e6a4b82f9bf2d388a18d07b92","cipher":"aes-128-ctr"},"address":"f8c2c1e3bd9b9c519a647b55db71adadba5da713"}

**Comment by ricardoak25** [comment]
https://github.com/CityOfZion/neo-swift/pull/104
