### ISSUE TITLE
Cannot get my assets

### ISSUE THREAD

**Issue by AlleniCode** [CityOfZion/neo-swift#63]
The Api 'public func getAccountState' in NeoClient.swift cannot gey my assets, but 'public func getAssets' can.

Testnet, address:AR4iFxFdbjTkHKtStSKRvu5bgXXBcpZx9D

**Comment by apisit** [comment]
Did you specify the full node URL for Testnet?

**Comment by AlleniCode** [comment]
fullNodeAPI = "http://testnet-api.wallet.cityofzion.io/v2/"

I'm not clear the difference between the 'sendRequest' and 'sendFullNodeRequest' .

**Comment by apisit** [comment]
@AlleniCode `sendFullNodeRequest` is used to fetch data like UTXO and balance  from CoZ's api endpoints

`getAccountState` should work as expected if you specify the NEO full node URL correctly.

Take a look here http://monitor.cityofzion.io/ and switch to TestNet to see which node you can make JSON-RPC call to.

**Comment by AlleniCode** [comment]
@apisit Thx, it works when I changed the seed to 'http://test5.cityofzion.io:8880'.

**Comment by apisit** [comment]
great.
