### ISSUE TITLE
How to auto select a best node in the test net nodes?

### ISSUE THREAD

**Issue by AlleniCode** [CityOfZion/neo-swift#64]
The func 'autoSelectBestNode' only can select a main net node, is there a func that I can select a test net node automatically？

**Comment by apisit** [comment]
You can add another function and pass the list of test node urls to it.

**Comment by AlleniCode** [comment]
I use the NeoSwift.framework in my iOS project, cannot add a func in it, cause my project limit that I cannot use the func 'NeoutilsSelectBestSeedNode()' in Neoutils.framework either, so would you like to add a func in  NeoSwift.framework that I can update the NeoSwift.framework in my project later? Thanks a lot!!!

**Comment by AlleniCode** [comment]
@apisit I use the NeoSwift.framework in my iOS project, cannot add a func in it, cause my project limit that I cannot use the func 'NeoutilsSelectBestSeedNode()' in Neoutils.framework either, so would you like to add a func in NeoSwift.framework that I can update the NeoSwift.framework in my project later? Thanks a lot!!!

**Comment by ricardoak25** [comment]
https://github.com/CityOfZion/neo-swift/pull/100
