### ISSUE TITLE
scrypt().scrypt very slow

### ISSUE THREAD

**Issue by ricardoak25** [CityOfZion/neo-swift#73]
When I try to open a wallet with encryptedPrivateKey and passphrase, its calling method NEP2.decryptKey.
The time to process scrypt().scrypt method is something close to 2 minutes. 
On neon-js the same method is very fast, about 3 seconds.
Probably there is some optimizations that could make it faster.

**Comment by lm2s** [comment]
You're probably running the app as Debug, which disables optimisations and makes the crypto code run pretty slow. You need to run as Release or enable optimisations on Debug (beware of weird behaviour on the debugger when optimisations are enabled).

**Comment by ricardoak25** [comment]
Thank you, running on release mode it worked. Now is about 4 seconds.
