### ISSUE TITLE
The API of Coz deprecated???

### ISSUE THREAD

**Issue by AlleniCode** [CityOfZion/neo-swift#75]
fullNodeAPI = "http://api.wallet.cityofzion.io/v2/"

enum apiURL: String {
        case getBalance = "address/balance/"
        case getClaims = "address/claims/"
        case getTransactionHistory = "address/history/"
    }

These API maybe deprecated, it failed when I called some func in NeoClient.

**Comment by saltyskip** [comment]
It seems to be deprecated, I am moving to new API's shortly, probably today

**Comment by ricardoak25** [comment]
https://github.com/CityOfZion/neo-swift/pull/109
